name: Gachigage Backend Develop Deploy

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Create resources directory & Set props
        run: |
          mkdir -p ./src/main/resources
          echo "${{secrets.APPLICATION}}" > ./src/main/resources/application.properties

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: SCP JAR to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          source: "build/libs/*.jar"
          target: "/${{secrets.SERVER_USER}}/gachigage/backend/"
          strip_components: 2

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          script: |
            cd /${{secrets.SERVER_USER}}/gachigage/backend
            
            rm *-plain.jar
            
            mv *.jar app.jar
            
            docker build -t gachigage-backend .
            
            docker compose up -d --no-deps backend
            
            docker image prune -f
